
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ATACAR CAMBIO COMENZAR COORDINATE DEFENDER ENEMIGO ESCANEAR PROPIO TABLEROcommand : action COORDINATE\n                | COMENZAR\n                | TABLERO bando\n                | CAMBIOaction : ATACAR\n              | DEFENDER\n              | ESCANEARbando : PROPIO\n             | ENEMIGO'
    
_lr_action_items = {'COMENZAR':([0,],[3,]),'TABLERO':([0,],[4,]),'CAMBIO':([0,],[5,]),'ATACAR':([0,],[6,]),'DEFENDER':([0,],[7,]),'ESCANEAR':([0,],[8,]),'$end':([1,3,5,9,10,11,12,],[0,-2,-4,-1,-3,-8,-9,]),'COORDINATE':([2,6,7,8,],[9,-5,-6,-7,]),'PROPIO':([4,],[11,]),'ENEMIGO':([4,],[12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'command':([0,],[1,]),'action':([0,],[2,]),'bando':([4,],[10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> action COORDINATE','command',2,'p_command','client_GUI_Aliados.py',47),
  ('command -> COMENZAR','command',1,'p_command','client_GUI_Aliados.py',48),
  ('command -> TABLERO bando','command',2,'p_command','client_GUI_Aliados.py',49),
  ('command -> CAMBIO','command',1,'p_command','client_GUI_Aliados.py',50),
  ('action -> ATACAR','action',1,'p_action','client_GUI_Aliados.py',54),
  ('action -> DEFENDER','action',1,'p_action','client_GUI_Aliados.py',55),
  ('action -> ESCANEAR','action',1,'p_action','client_GUI_Aliados.py',56),
  ('bando -> PROPIO','bando',1,'p_bando','client_GUI_Aliados.py',60),
  ('bando -> ENEMIGO','bando',1,'p_bando','client_GUI_Aliados.py',61),
]
