
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ATACAR COORDINATE DEFENDERcommand : action COORDINATEaction : ATACAR\n              | DEFENDER'
    
_lr_action_items = {'ATACAR':([0,],[3,]),'DEFENDER':([0,],[4,]),'$end':([1,5,],[0,-1,]),'COORDINATE':([2,3,4,],[5,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'command':([0,],[1,]),'action':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> action COORDINATE','command',2,'p_command','main.py',23),
  ('action -> ATACAR','action',1,'p_action','main.py',27),
  ('action -> DEFENDER','action',1,'p_action','main.py',28),
]
