
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ATACAR COMENZAR COORDINATE DEFENDERcommand : action COORDINATE\n               | COMENZARaction : ATACAR\n              | DEFENDER'
    
_lr_action_items = {'COMENZAR':([0,],[3,]),'ATACAR':([0,],[4,]),'DEFENDER':([0,],[5,]),'$end':([1,3,6,],[0,-2,-1,]),'COORDINATE':([2,4,5,],[6,-3,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'command':([0,],[1,]),'action':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> action COORDINATE','command',2,'p_command','client_GUI.py',34),
  ('command -> COMENZAR','command',1,'p_command','client_GUI.py',35),
  ('action -> ATACAR','action',1,'p_action','client_GUI.py',39),
  ('action -> DEFENDER','action',1,'p_action','client_GUI.py',40),
]
